name: blendshapes
channels:
  - pytorch3d
  - bottler
  - iopath
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - backcall=0.2.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - comm=0.2.1
  - cryptography=41.0.7
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=12.3.101
  - cuda-libraries=11.6.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.3.101
  - cuda-nsight-compute=12.3.2
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.3.101
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.3.101
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.3.101
  - cuda-runtime=11.6.1
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=12.3.101
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-visual-tools=11.6.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=2.0.1
  - ffmpeg=4.3
  - freetype=2.12.1
  - fvcore=0.1.5.post20221221
  - gds-tools=1.8.1.2
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2023.1.0
  - iopath=0.1.9
  - ipykernel=6.29.0
  - ipython=8.12.0
  - jedi=0.19.1
  - jpeg=9e
  - jupyter_client=7.3.4
  - jupyter_core=5.7.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcufile=1.8.1.2
  - libcufile-dev=1.8.1.2
  - libcurand=10.3.4.107
  - libcurand-dev=10.3.4.107
  - libcusolver=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - nsight-compute=2023.3.1.1
  - numpy=1.26.3
  - numpy-base=1.26.3
  - nvidiacub=1.10.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.12
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3.1
  - platformdirs=4.1.0
  - portalocker=2.8.2
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.17.2
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.13.0
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - pytorch3d=0.7.5
  - pyyaml=6.0
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tabulate=0.9.0
  - tbb=2021.8.0
  - termcolor=2.4.0
  - tk=8.6.12
  - torchvision=0.14.0
  - tornado=6.1
  - tqdm=4.66.1
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - tzdata=2023d
  - urllib3=1.26.18
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.5
  - yacs=0.1.8
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - attrs==23.2.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - flatbuffers==23.5.26
      - fonttools==4.47.2
      - imageio==2.25.0
      - imageio-ffmpeg==0.4.9
      - importlib-resources==6.1.1
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - matplotlib==3.8.2
      - mediapipe==0.10.9
      - networkx==3.2.1
      - opencv-contrib-python==4.9.0.80
      - protobuf==3.20.3
      - pyparsing==3.1.1
      - pywavelets==1.5.0
      - scikit-image==0.18.3
      - scipy==1.12.0
      - sounddevice==0.4.6
      - tifffile==2023.12.9
      - zipp==3.17.0
